apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.global.namespace }}
data:
  runtime-config.js: |
    window.WORDWANK_CONFIG = {
      LOG_LEVEL: {{ .Values.global.logLevel | default .Values.logLevel | quote }}
    };
