replicaCount: 1
image:
  repository: localhost:5000/wordwank-backend
  pullPolicy: Always
  tag: "0.23.0"
  logLevel: debug
service:
  type: ClusterIP
  port: 3000
database:
  url: "dbi:Pg:dbname=wordwank;host=postgresql"
  user: "postgres"
