apiVersion: v1
kind: ConfigMap
metadata:
  name: wordwank-locales
  namespace: {{ .Values.global.namespace }}
data:
  en.json: |-
{{ .Files.Get "share/locale/en.json" | nindent 4 }}
  es.json: |-
{{ .Files.Get "share/locale/es.json" | nindent 4 }}
  fr.json: |-
{{ .Files.Get "share/locale/fr.json" | nindent 4 }}
  de.json: |-
{{ .Files.Get "share/locale/de.json" | nindent 4 }}
  ru.json: |-
{{ .Files.Get "share/locale/ru.json" | nindent 4 }}

