apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.global.namespace | default "wordwank" }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
  backend-db-user: {{ .Values.backend.database.user | quote }}
  backend-db-pass: {{ .Values.postgresql.auth.password | quote }}
  google-client-id: {{ .Values.auth.google.clientId | quote }}
  google-client-secret: {{ .Values.auth.google.clientSecret | quote }}
