apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordwank-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /tm
            pathType: Prefix
            backend:
              service:
                name: tilemasters
                port:
                  number: {{ .Values.tilemasterd.service.port }}
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: gatewayd
                port:
                  number: {{ .Values.gatewayd.service.port }}
          - path: /players
            pathType: Prefix
            backend:
              service:
                name: playerd
                port:
                  number: {{ .Values.playerd.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.service.port }}
