apiVersion: v2
name: wordwank
description: Umbrella chart for the Wordwank polyglot microservices stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://../../srv/frontend/helm"
  - name: gatewayd
    version: 0.1.0
    repository: "file://../../srv/gatewayd/helm"
  - name: tilemasterd
    version: 0.1.0
    repository: "file://../../srv/tilemasters/helm"
  - name: playerd
    version: 0.1.0
    repository: "file://../../srv/playerd/helm"
  - name: wordd
    version: 0.1.0
    repository: "file://../../srv/wordd/helm"
  - name: dictd
    version: 0.1.0
    repository: "file://../../srv/dictd/helm"
