apiVersion: v2
name: wordwank
description: Umbrella chart for the Wordwank polyglot microservices stack
type: application
version: 0.10.0
appVersion: "0.10.0"

dependencies:
  - name: frontend
    version: 0.10.0
    repository: "file://../../srv/frontend/helm"
  - name: gatewayd
    version: 0.10.0
    repository: "file://../../srv/gatewayd/helm"
  - name: tilemasterd
    version: 0.10.0
    repository: "file://../../srv/tilemasters/helm"
  - name: playerd
    version: 0.10.0
    repository: "file://../../srv/playerd/helm"
  - name: wordd
    version: 0.10.0
    repository: "file://../../srv/wordd/helm"
  - name: dictd
    version: 0.10.0
    repository: "file://../../srv/dictd/helm"
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
