# Global settings shared across all microservices
global:
  domain: wordwank.local
  # The single port for all traffic (Frontend, API, WS)
  externalPort: 8888
  registry: docker.io/wordwank
  namespace: wordwank
  imageTag: latest
  imagePullPolicy: Always

# Subchart overrides
frontend:
  service:
    type: LoadBalancer
    port: 80

gatewayd:
  service:
    type: ClusterIP
    port: 8081

tilemasterd:
  service:
    type: ClusterIP
    port: 3883

playerd:
  service:
    type: ClusterIP
    port: 8080
  redis:
    host: redis-master

wordd:
  service:
    type: ClusterIP
    port: 2345

dictd:
  service:
    type: ClusterIP
    port: 2628
