# Global settings shared across all microservices
global:
  domain: arkham.fazigu.org
  # The single port for all traffic (Frontend, API, WS)
  externalPort: 80
  registry: localhost:5000
  namespace: wordwank
  imageTag: latest
  imagePullPolicy: IfNotPresent

# Centralized Ingress configuration
ingress:
  enabled: true
  host: arkham.fazigu.org
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

# Subchart overrides
frontend:
  service:
    type: ClusterIP
    port: 80

gatewayd:
  service:
    type: ClusterIP
    port: 8081

tilemasterd:
  service:
    type: ClusterIP
    port: 3883

playerd:
  service:
    type: ClusterIP
    port: 8080
  redis:
    host: redis-master

wordd:
  service:
    type: ClusterIP
    port: 2345

dictd:
  service:
    type: ClusterIP
    port: 2628
