apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gatewayd
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayd
  template:
    metadata:
      labels:
        app: gatewayd
    spec:
      containers:
        - name: gatewayd
          image: "{{ .Values.global.registry }}/gatewayd:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayd
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
  selector:
    app: gatewayd
