apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minikube-pool
  namespace: metallb-system
spec:
  addresses:
    - RANGE_START-RANGE_END
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: minikube-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - minikube-pool
