apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-playerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playerd
  template:
    metadata:
      labels:
        app: playerd
    spec:
      containers:
        - name: playerd
          image: "{{ .Values.global.registry }}/playerd:latest"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: {{ .Values.redis.host }}
---
apiVersion: v1
kind: Service
metadata:
  name: playerd
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: playerd
